server:
  error:
    include-message: always
    include-binding-errors: always

#mysql://b087565cacb75e:5c6012f8@us-cdbr-east-06:cleardb:net/heroku_dc4d2f6f3feff93?reconnect=true
spring:
  datasource:
#    password: "5c6012f8"
#    url: "jdbc:mysql://us-cdbr-east-06.cleardb.net/heroku_dc4d2f6f3feff93?reconnect=true"
#    username: "b087565cacb75e"
#    LOCAL HOST
    password:
    url: "jdbc:mysql://localhost:3306/predictz_db?reconnect=true"
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000