server:
  error:
    include-message: always
    include-binding-errors: always

#mysql://b087565cacb75e:5c6012f8@us-cdbr-east-06:cleardb:net/heroku_dc4d2f6f3feff93?reconnect=true
spring:
  datasource:
#    password: "pscale_pw_T0AG1XnigDmHfil4NJdGBL1s5SMat0rPO1SHccLSDeB"
#    url: "jdbc:mysql://us-east.connect.psdb.cloud/predictz_db?sslMode=VERIFY_IDENTITY"
#    username: "jb12dc602kup279ajcvx"

#    Heroku clearDb
    password: "5c6012f8"
    url: "jdbc:mysql://us-cdbr-east-06.cleardb.net/heroku_dc4d2f6f3feff93?reconnect=true"
    username: "b087565cacb75e"

#    LOCAL HOST
#    password:
#    url: "jdbc:mysql://localhost:3306/predictz_db?reconnect=true"
#    username: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: false